---
- name: Update & Upgrade packages
  apt:
    update_cache: yes
    upgrade: full
    autoclean: yes
    autoremove: yes
  tags: update

- name: Install Packages
  apt:
    state: present
    install_recommends: no
    pkg:
      - python3
      - cifs-utils
      - fail2ban
      - cryptsetup
      - gpg
      - gpg-agent
      - rsync
      - dnsutils
      - python3-llfuse
      - jq
      - direnv
      - git
      - htop
      - autojump
      - build-essential
      - vim
      - iptables-persistent
      - zsh
