version: '3.9'
services:
  web:
    image: ghcr.io/0pss/alpakabook:docker
    container_name: alpakabook
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - web
    # volumes:
    #   - "{{ data_dir.path }}/db.sqlite3:/app/db.sqlite3"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ role_name }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ role_name }}.entrypoints=https
      - traefik.http.routers.{{ role_name }}.tls=true
      - traefik.http.routers.{{ role_name }}.tls.certresolver=letsencrypt
      - traefik.http.services.{{ role_name }}.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true

networks:
  web:
    external:
      name: traefik_web
