---
- name: Create user {{ username }}
  tags: user
  user:
    name: "{{ username }}"
    shell: "/bin/zsh"
    generate_ssh_key: true
    append: true
    groups:
      - docker
      - admin

- name: Set authorized keys
  tags: user
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_key }}"
