---
- name: "Create dir for docker file"
  tags: jupyter
  file:
    path: '{{ docker_compose_root }}/{{ role_name }}/{{ domain.split(".")[0] }}'
    state: directory
  register: docker_dir

- name: "Create store dir"
  tags: jupyter
  file:
    path: '{{ storage_root }}/{{ role_name }}/{{ domain.split(".")[0] }}'
    state: directory
  register: store_dir

- name: "Create data dir"
  tags: jupyter
  file:
    path: "{{ store_dir.path }}/data"
    state: directory
    mode: 0755
    owner: 1000
  register: data_dir

- name: "Render docker-compose"
  tags: jupyter
  template:
    src: docker-compose.yml
    dest: "{{ docker_dir.path }}/docker-compose.yml"
    mode: 0644
  register: docker

- name: "start docker service"
  tags: [jupyter, update]
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir.path }}"
    remove_orphans: true
    pull: always
    state: present
