---
- name: "Create dir for docker file"
  file:
    path: "{{ docker_compose_root }}/{{ role_name }}"
    state: directory
  register: docker_dir

- name: "Create store dir"
  file:
    path: "{{ storage_root }}/{{ role_name }}"
    state: directory
  register: store_dir

- name: "Create data dir"
  file:
    path: "{{ store_dir.path }}/data"
    state: directory
  register: data_dir

- name: "Render docker-compose"
  template:
    src: docker-compose.yml
    dest: "{{ docker_dir.path }}/docker-compose.yml"
    mode: 0644
  register: docker

- name: "start docker service"
  community.docker.docker_compose:
    project_src: "{{ docker_dir.path }}"
    pull: yes
    state: present
    restarted: "{{ docker.changed }}"
